### ISSUE TITLE
Accurate Vs. Fast

### ISSUE THREAD

**Issue by Halasa962** [glichtner/pystackreg#25]
Hello, 
In the Fiji plugin, TurboReg offers the possibility between registering the image either fast or accurate. Is this also offered in the pystack reg package. I looked at the documentation and code, and it seems like it does not have that option. Am I correct, or missing something?

Thank you for your help

Best,

**Comment by glichtner** [comment]
Hi,

you are correct, the pystackreg package only uses the "accurate" method of TubroReg as I think that it runs fast enough on any modern computer to not require a faster option.

Best,
Gregor

**Comment by Halasa962** [comment]
Hello, 

I have compared both outputs from turboReg Fiji, and pyStackReg. In the Fiji case, I always convert from 32 bit to 16 bit. Also, In the pyStackReg I used the function provided by the algorithm(util functions). Though, I have seen differences in data ranges. My data is a time series data image stack (x,y,t), I visualzed the same ROI from both images by clicking the plot z-axis profile across time. Why do you think this might happen? 

thank you a lot
Best,
Khaleel

**Comment by glichtner** [comment]
Hey, 
could have multiple reasons, I don't have enough information. For example, maybe Fiji converts 32 bit differently to 16 bit than does pystackreg (e.g. not clipping, or downsampling). Can you provide example data and a detailed workflow for Fiji and a Python script that shows your approach?
Otherwise, how large are the differences?
With the same input and options, pystackreg and the Fiji plugin should result in the exact same images.
Did you use the fast option in Fiji maybe? Or a different transformation type?
