### ISSUE TITLE
Is it able to do registration with different image sizes?

### ISSUE THREAD

**Issue by PikaPei** [glichtner/pystackreg#29]
Hello!

May I ask a question here? Hope it won't bother you too much.
I'm not familiar with the registration method.
I wonder why this package can't apply to images with different sizes?

Thank you!

**Comment by glichtner** [comment]
Hi,

In fact, registration can only be done for images of the same size. If your images are of different sizes, you can either crop the larger image to fit the smaller image or enlarge the smaller image to fit the larger image (using zero padding, for example). Since both methods can lead to different results and the images are usually the same size for registration, it is up to the user to prepare their images accordingly to the same size.

The transformation can then be performed on any image of any size, since it is merely an affine (or bilinear) transformation.

Hope that helps.
